steps:
  # Step 1: Install dependencies and run comprehensive tests
  - name: 'node:20'
    id: 'install-deps'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:20'
    id: 'run-all-tests'
    entrypoint: 'npm'
    args: ['run', 'test:all']
    env:
      - 'NODE_ENV=test'

  # Step 2: Build Docker image with production optimizations
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/adria-website:prod-$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/adria-website:prod-latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/adria-website:$TAG_NAME'
      - '--build-arg'
      - 'BUILD_ENV=production'
      - '.'

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/adria-website'

  # Step 4: Create backup of current production deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'backup-current'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating backup of current production deployment..."
        chmod +x ./scripts/backup-deployment.sh
        ./scripts/backup-deployment.sh production

  # Step 5: Run database migrations with backup
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running database migrations for production..."
        chmod +x ./scripts/run-migrations.sh
        ./scripts/run-migrations.sh production

  # Step 6: Deploy to Cloud Run (Production) with gradual rollout
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-production'
    args:
      - 'run'
      - 'deploy'
      - 'adria-website-prod'
      - '--image'
      - 'gcr.io/$PROJECT_ID/adria-website:prod-$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--set-secrets'
      - 'DATABASE_URL=PROD_DATABASE_URL:latest,JWT_SECRET=PROD_JWT_SECRET:latest,SENDGRID_API_KEY=PROD_SENDGRID_API_KEY:latest,STRIPE_SECRET_KEY=PROD_STRIPE_SECRET_KEY:latest,GOOGLE_CALENDAR_CREDENTIALS=PROD_GOOGLE_CALENDAR_CREDENTIALS:latest'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '100'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--port'
      - '8080'
      - '--no-traffic'

  # Step 7: Run comprehensive smoke tests
  - name: 'node:20'
    id: 'smoke-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running smoke tests against new production revision..."
        chmod +x ./scripts/smoke-tests.sh
        ./scripts/smoke-tests.sh production-candidate

  # Step 8: Gradual traffic migration (0% -> 25% -> 50% -> 100%)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'gradual-rollout'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting gradual traffic rollout..."
        chmod +x ./scripts/gradual-rollout.sh
        ./scripts/gradual-rollout.sh adria-website-prod us-central1

  # Step 9: Monitor deployment health
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'monitor-health'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Monitoring deployment health for 5 minutes..."
        chmod +x ./scripts/monitor-health.sh
        ./scripts/monitor-health.sh adria-website-prod us-central1 300

  # Step 10: Send deployment notification
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'notify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Production deployment completed successfully!"
        echo "Image: gcr.io/$PROJECT_ID/adria-website:prod-$SHORT_SHA"
        echo "Service URL: https://adriacross.com"
        echo "Rollback available via: ./scripts/rollback.sh production <previous-revision>"

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/adria-website:prod-$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/adria-website:prod-latest'

# Build configuration
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON

# Timeout for entire build (30 minutes to allow for gradual rollout)
timeout: '1800s'

# Substitutions
substitutions:
  _DEPLOY_REGION: 'us-central1'
  _SERVICE_NAME: 'adria-website-prod'

# Tags for build tracking
tags:
  - 'production'
  - 'adria-website'
  - 'automated-deployment'
